spring:

  datasource:
    url: "jdbc:postgresql://localhost:2345/car-db"
    username: "admin"
    password: "admin"

  jpa:
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://infinum.com"
          jwk-set-uri: "http://localhost:8888/jwks.json"
