version: "3"

# docker run --rm --name car-database -v car-db-data:/var/lib/postgresql/data -p 2345:5432
# -e POSTGRES_PASSWORD=admin -e POSTGRES_DB=courses-db -d postgres:13-alpine
services:
    car-database:
        image: "postgres:13-alpine"
        ports:
            - "2345:5432"
        volumes:
            - "car-db-data:/var/lib/postgresql/data"
        environment:
            - "POSTGRES_USER=admin"
            - "POSTGRES_PASSWORD=admin"
            - "POSTGRES_DB=car-db"
volumes:
    car-db-data:
