ALTER TABLE cars RENAME COLUMN carId TO id;
ALTER TABLE cars ALTER COLUMN ownerId TYPE BIGINT;
ALTER TABLE cars ALTER COLUMN ownerId SET NOT NULL;
ALTER TABLE checkups RENAME COLUMN checkUpId TO id;
ALTER TABLE checkups ALTER COLUMN carId TYPE BIGINT;
ALTER TABLE checkups ALTER COLUMN carId SET NOT NULL;
ALTER TABLE checkups ADD CONSTRAINT fk_cars FOREIGN KEY(carId) REFERENCES cars(id);